=== CBIIT/common-security-module/cgmmweb/resources/cgmm-properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="authentication-service-information">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service-name"/>
				<xs:element ref="service-url"/>
				<xs:element ref="dorian-information"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="authentication-service-list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="authentication-service-information" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dorian-information">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service-url"/>
				<xs:element ref="proxy-lifetime-hours"/>
				<xs:element ref="proxy-lifetime-minutes"/>
				<xs:element ref="proxy-lifetime-seconds"/>
				<xs:element ref="proxy-delegation-path-length"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cgmm-information">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cgmm-context-name"/>
				<xs:element ref="start-auto-syncgts"/>
				<xs:element ref="cgmm-ui-host-application-logo"/>
				<xs:element ref="cgmm-ui-menu-display-value-for-csm"/>
				<xs:element ref="cgmm-ui-menu-display-value-for-grid"/>
				<xs:element ref="cgmm-new-grid-user-creation-disabled"/>
				<xs:element ref="cgmm-new-grid-user-creation-host-redirect-uri"/>
				<xs:element ref="error-messages"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="host-application-information">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="host-context-name"/>
				<xs:element ref="host-public-home-page-url"/>
				<xs:element ref="host-user-home-page-url"/>
				<xs:element ref="host-new-local-user-creation-url"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="error-messages">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="error-csm-invalid-credentials" type="xs:string"/>
				<xs:element name="error-grid-invalid-credentials" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cgmm-new-grid-user-creation-disabled" type="xs:string"/>
	<xs:element name="cgmm-new-grid-user-creation-host-redirect-uri" type="xs:string" nillable="true"/>
	<xs:element name="cgmm-context-name" type="xs:string"/>
	<xs:element name="cgmm-ui-menu-display-value-for-csm" type="xs:string"/>
	<xs:element name="cgmm-ui-menu-display-value-for-grid" type="xs:string"/>
	<xs:element name="cgmm-ui-host-application-logo" type="xs:string"/>
	<xs:element name="host-context-name" type="xs:string"/>
	<xs:element name="host-public-home-page-url" type="xs:string"/>
	<xs:element name="host-user-home-page-url" type="xs:string"/>	
	<xs:element name="host-new-local-user-creation-url" type="xs:string"/>
	<xs:element name="start-auto-syncgts" type="xs:string"/>
	<xs:element name="host-credential-certificate-file-path" type="xs:string"/>
	<xs:element name="host-credential-key-file-path" type="xs:string"/>
	<xs:element name="group-name" type="xs:string"/>
	<xs:element name="host-identity" type="xs:string"/>
	<xs:element name="service-name" type="xs:string"/>
	<xs:element name="service-url" type="xs:anyURI"/>
	<xs:element name="proxy-lifetime-hours" type="xs:integer"/>
	<xs:element name="proxy-lifetime-minutes" type="xs:integer"/>
	<xs:element name="proxy-lifetime-seconds" type="xs:integer"/>
	<xs:element name="proxy-delegation-path-length" type="xs:integer"/>
	<xs:element name="cgmm-properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="cgmm-information"/>
				<xs:element ref="host-application-information"/>
				<xs:element ref="authentication-service-list"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CBIIT/common-security-module/software/cgmmweb/resources/cgmm-properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<cgmm-properties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cgmm-properties.xsd">
	<cgmm-information>
		<cgmm-context-name>cgmmweb</cgmm-context-name>
		<cgmm-login-config-file-name>cgmm.login.config</cgmm-login-config-file-name>
		<start-auto-syncgts>true</start-auto-syncgts>
		<cgmm-new-grid-user-creation-disabled>false</cgmm-new-grid-user-creation-disabled>
		<cgmm-new-grid-user-creation-host-redirect-uri>/public/newGridUserCreation.jsp</cgmm-new-grid-user-creation-host-redirect-uri>
	</cgmm-information>
	<host-application-information>
		<host-context-name>cgmmhostweb</host-context-name>
		<host-application-name-for-csm>sampleHostApplicationContextName</host-application-name-for-csm>
		<host-public-home-page-url>/public/publicHome.jsp</host-public-home-page-url>
		<host-user-home-page-url>/secured/userHomePage.jsp</host-user-home-page-url>		
		<host-new-local-user-creation-url>/public/newLocalUserCreation.jsp</host-new-local-user-creation-url>
	</host-application-information>
	<authentication-service-list>
		<authentication-service-information>
			<service-name>caGrid Training</service-name>
			<service-url>https://dorian.training.cagrid.org:8443/wsrf/services/cagrid/Dorian</service-url>
			<dorian-information>
				<service-url>https://dorian.training.cagrid.org:8443/wsrf/services/cagrid/Dorian</service-url>
				<proxy-lifetime-hours>12</proxy-lifetime-hours>
				<proxy-lifetime-minutes>0</proxy-lifetime-minutes>
				<proxy-lifetime-seconds>0</proxy-lifetime-seconds>
				<proxy-delegation-path-length>3</proxy-delegation-path-length>
			</dorian-information>
		</authentication-service-information>
	</authentication-service-list>
</cgmm-properties>
